import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatMoney, formatDate } from './format.js'

export function exportMonthToPDF({ month, loans, loanerNameFor, settings, cash }) {
  const currency = settings?.currency || 'R'
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(17, 17, 40)
  doc.text('Loan Summary Report', margin, 56)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(100, 100, 120)
  doc.text(month?.label || '', margin, 74)
  doc.text(`Generated on: ${formatDate(new Date())}`, pageWidth - margin, 56, { align: 'right' })
  doc.text(`Total Loans: ${loans.length}`, pageWidth - margin, 74, { align: 'right' })

  // Stat cards
  const stats = [
    { label: 'Total Money Out', value: formatMoney(cash.totalMoneyOutMonth, currency) },
    { label: 'Total to Collect', value: formatMoney(cash.totalToCollectMonth, currency) },
    { label: 'Total Collected', value: formatMoney(cash.totalCollectedMonth, currency) },
    { label: 'Outstanding', value: formatMoney(cash.totalToCollectMonth, currency) }
  ]
  const cardW = (pageWidth - margin * 2 - 30) / 4
  let cx = margin
  const cardY = 96
  stats.forEach((s) => {
    doc.setFillColor(246, 247, 251)
    doc.roundedRect(cx, cardY, cardW, 56, 6, 6, 'F')
    doc.setFontSize(9)
    doc.setTextColor(110, 110, 130)
    doc.text(s.label, cx + 10, cardY + 20)
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(20, 20, 40)
    doc.text(s.value, cx + 10, cardY + 40)
    doc.setFont('helvetica', 'normal')
    cx += cardW + 10
  })

  // Table
  const rows = loans.map((l) => [
    loanerNameFor(l.loanerId),
    formatMoney(l.amount, currency),
    `${l.interestPercent}%`,
    formatMoney(l.total, currency),
    formatMoney(l.paidAmount, currency),
    formatMoney(l.balance, currency),
    l.status,
    formatDate(l.dueDate)
  ])
  const totals = {
    amount: loans.reduce((s, l) => s + l.amount, 0),
    total: loans.reduce((s, l) => s + l.total, 0),
    paid: loans.reduce((s, l) => s + l.paidAmount, 0),
    balance: loans.reduce((s, l) => s + l.balance, 0)
  }

  autoTable(doc, {
    startY: cardY + 76,
    margin: { left: margin, right: margin },
    head: [['Loaner', 'Amount', 'Interest', 'Total', 'Paid', 'Balance', 'Status', 'Due Date']],
    body: rows,
    foot: [['Total', formatMoney(totals.amount, currency), '', formatMoney(totals.total, currency), formatMoney(totals.paid, currency), formatMoney(totals.balance, currency), '', '']],
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 6, textColor: [30, 30, 50] },
    headStyles: { fillColor: [17, 17, 40], textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [246, 247, 251], textColor: [17, 17, 40], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [250, 250, 253] }
  })

  const finalY = doc.lastAutoTable.finalY || cardY + 76
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 165)
  doc.text('Generated by Loan Shark — 100% offline, no data leaves this device.', margin, finalY + 24)

  return doc
}

export function downloadMonthPDF(args) {
  const doc = exportMonthToPDF(args)
  const filename = `loan-summary-${args.month?.key || 'export'}.pdf`
  doc.save(filename)
}
